### ISSUE TITLE
Different Classes for the same role

### ISSUE THREAD

**Issue by Malo-35** [MrAfitol/InventoryControl#5]
Hello, I wanted to make different classes in a same role type.
Let me explain :
When a player spawn as a FacilityGuard I want him to have one of the three classes :
Knight-type-Guard :
- Jailbird
- ArmorCombat
- Adrenaline
- Radio

Trigger-type-Guard :
- COM-45
- *A lot of ammo
- Radio
- Painkillers

Classic-type-Guard :
- The basic stuff

Is it possible to do such a thing ?

**Comment by MrAfitol** [comment]
Hello, that's a good idea!

**Comment by MrAfitol** [comment]
Hi again, this has been added to the new version of the plugin, thanks again for the idea.
[Version 1.1.3](https://github.com/MrAfitol/InventoryControl/releases/tag/1.1.3)
